name: CI
permissions: {}

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "patches/v20*.patch"
      - "resources/**"
      - "scripts/**"
      - "Dockerfile"

jobs:
  docker-build:
    name: Test building web-vault
    permissions:
      packages: write # Needed to upload packages and artifacts
      contents: read
    runs-on: ubuntu-latest
    env:
      # Force docker to output the progress in plain
      BUILDKIT_PROGRESS: plain
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Build and Extract
        shell: bash
        run: |
          make docker-extract

      - name: Generate checksum
        shell: bash
        run: |
          echo "sha256sum: $(sha256sum container_builds/bw_web_vault.tar.gz)"

      - name: "Upload web-vault artifact"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: web-vault
          compression-level: 0
          path: container_builds/bw_web_vault.tar.gz
